package com.priyanshu.upifraudshieldai.transaction.dto;

import lombok.*;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FraudCheckResponse
{

    private boolean fraud;

    // 0.0 = clean, 1.0 = definitely fraud
    private double fraudScore;

    // List of rule codes that fired e.g. ["RULE_HIGH_AMOUNT", "RULE_NEW_DEVICE"]
    private List<String> triggeredRules;

    // Natural language explanation generated by the LLM
    private String explanation;

    // ALLOW, FLAG, BLOCK
    private String recommendation;
}